sudo: required
language :
  - go
os:
  - linux
services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  bundler: false
  directories:
  - .build-cache
# Handle git submodules yourself
git:
    submodules: false
# Do a github login using token

install:
  - go get -u github.com/ains/go-test-html
  - go get github.com/project-flogo/cli
  - pip install --user awscli

script:
  - go test ./... -v 2> >(tee gotest_stderr_file) | tee gotest_stdout_file
  - go install ./...
  - chmod ugo+x ./build.sh
  - ./build.sh

notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - jpark@tibco.com
      - rpolishe@tibco.com
      - lmekala@tibco.com
      - nthota@tibco.com
      - ykalidin@tibco.com
      - jbozek@tibco.com
      - asnodgra@tibco.com
      - agadikar@tibco.com
